<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthSystem.Application\AuthSystem.Application.csproj" />
    <ProjectReference Include="..\AuthSystem.Domain\AuthSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Helpers\" />
    <Folder Include="Services\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
